// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentExperiment() {
  return window['go']['main']['App']['GetCurrentExperiment']();
}

export function SaveCurrentExperiment(arg1) {
  return window['go']['main']['App']['SaveCurrentExperiment'](arg1);
}
