// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetCurrentExperiment():Promise<models.Experiment>;

export function SaveCurrentExperiment(arg1:models.Experiment):Promise<boolean>;
